import type { CSSProperties } from 'react';
import { FAQ, FLAVORS, PROCESS, type FlavorKey } from '../data';
import Icon from './Icon';

export default function Operations({ allocation, setAllocation, faq, setFaq }: { allocation: Record<FlavorKey,number>; setAllocation: (v: Record<FlavorKey,number>)=>void; faq: number|null; setFaq: (v:number|null)=>void }) {
  const total = Object.values(allocation).reduce((a,b)=>a+b,0);
  const change=(key:FlavorKey,delta:number)=>setAllocation({...allocation,[key]:Math.max(0,Math.min(300,allocation[key]+delta))});
  return <>
    <section id="processo" className="fp-section fp-dark"><div className="fp-section-head"><div><span>04 · Jornada de produção</span><h2>Da decisão à expedição, sem ruído.</h2></div><p>Um fluxo visual com responsabilidades claras reduz retrabalho e protege o prazo.</p></div><div className="fp-process">{PROCESS.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
    <section id="condicoes" className="fp-section"><div className="fp-section-head"><div><span>05 · Prazos e condições</span><h2>Regras simples. Execução protegida.</h2></div><p>O prazo começa quando tudo o que depende das duas empresas estiver disponível e aprovado.</p></div><div className="fp-conditions">{[[<Icon key="a" name="shield"/>,'50% + 50%','Entrada na aprovação e saldo antes da expedição.'],[<Icon key="b" name="clock"/>,'10 dias úteis','Após materiais, aprovação técnica e pagamento.'],[<Icon key="c" name="clock"/>,'7 dias corridos','Validade comercial desta proposta.'],[<Icon key="d" name="arrow"/>,'Frete FLYPRO','Envio de materiais e retirada por conta da contratante.']].map(([i,t,d])=><article key={String(t)}><div>{i}</div><strong>{t}</strong><p>{d}</p></article>)}</div><div className="fp-legal"><Icon name="shield"/><div><h3>Homologação e proteção do conhecimento técnico</h3><p>A Vita Power indicará fornecedores homologados. Outros fornecedores exigem avaliação prévia e documentação técnica. No Modelo 2, a FLYPRO enviará 4% de excedente dos materiais sob sua responsabilidade.</p><p>A formulação-base, o sistema sensorial, as proporções e os parâmetros de processo permanecem como propriedade intelectual da Vita Power.</p></div></div></section>
    <section className="fp-section fp-simulator"><div className="fp-section-head"><div><span>06 · Laboratório de decisão</span><h2>Simule a distribuição dos sabores.</h2></div><p>Uma ferramenta visual para a conversa comercial. A divisão definitiva será confirmada formalmente.</p></div><div className="fp-allocation">{FLAVORS.map(item=><article key={item.key} style={{'--accent':item.accent} as CSSProperties}><img src={item.image} alt={item.key} style={{objectPosition:item.position}}/><h3>{item.key}</h3><div><button onClick={()=>change(item.key,-5)}>−</button><strong>{allocation[item.key]}</strong><button onClick={()=>change(item.key,5)}>+</button></div></article>)}</div><div className={`fp-allocation-total ${total===300?'ok':'warn'}`}><div><span>Total simulado</span><strong>{total} / 300 unidades</strong></div><button onClick={()=>setAllocation({Chocolate:75,Baunilha:75,Morango:75,'Cookies & Cream':75})}>Dividir igualmente</button></div></section>
    <section id="proximos" className="fp-section fp-dark"><div className="fp-section-head"><div><span>07 · Próximos passos</span><h2>Quatro decisões até o início.</h2></div><p>A proposta define o cenário comercial. A etapa seguinte transforma escolhas em ordem de produção.</p></div><div className="fp-next">{[['01','Escolher o modelo','Produto completo ou industrialização.'],['02','Definir o formato','Pote ou pouch e especificações.'],['03','Fechar sabores e arte','Distribuição, dizeres e conferência.'],['04','Liberar produção','Pagamento, materiais e ordem formal.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="fp-faq"><div><span>FAQ</span><h3>Tudo o que precisa estar claro.</h3></div><div>{FAQ.map(([q,a],i)=><article key={q} className={faq===i?'open':''}><button onClick={()=>setFaq(faq===i?null:i)}><span>{q}</span><b>{faq===i?'−':'+'}</b></button><p>{a}</p></article>)}</div></div></section>
  </>;
}
